### ISSUE TITLE
java.lang.UnsatisfiedLinkError on mac m1

### ISSUE THREAD

**Issue by dswiecki** [ververica/frocksdb#43]
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/9w/kbk7nnxd60jf5lqgp4vgm5kh0000gn/T/junit12882793858522803468/junit18283359092312814966/rocksdb-lib-c06728cfa5b110c51f7e8f16aa883bc0/librocksdbjni-osx.jnilib: dlopen(/private/var/folders/9w/kbk7nnxd60jf5lqgp4vgm5kh0000gn/T/junit12882793858522803468/junit18283359092312814966/rocksdb-lib-c06728cfa5b110c51f7e8f16aa883bc0/librocksdbjni-osx.jnilib, 0x0001): tried: '/private/var/folders/9w/kbk7nnxd60jf5lqgp4vgm5kh0000gn/T/junit12882793858522803468/junit18283359092312814966/rocksdb-lib-c06728cfa5b110c51f7e8f16aa883bc0/librocksdbjni-osx.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57)
        at org.apache.flink.contrib.streaming.state.EmbeddedRocksDBStateBackend.ensureRocksDBIsLoaded(EmbeddedRocksDBStateBackend.java:856)
        ... 18 more

releated issue in rocksdb https://github.com/facebook/rocksdb/issues/9721
releated issue in flink https://issues.apache.org/jira/browse/FLINK-26876

**Comment by Myasuka** [comment]
Hi, sorry for the late reply, this problem is tracked by https://github.com/ververica/frocksdb/pull/50
